import { NextResponse } from "next/server";
import nodemailer from "nodemailer";

export async function POST(request: Request) {
  try {
    const { name, email, projectType, budgetRange, timeline, message } = await request.json();

    if (!name || !email || !message) {
      return NextResponse.json(
        { success: false, error: "Name, email, and message are required." },
        { status: 400 }
      );
    }

    const host = process.env.SMTP_HOST;
    const port = parseInt(process.env.SMTP_PORT || "587");
    const user = process.env.SMTP_USER;
    const pass = process.env.SMTP_PASSWORD;
    const receiver = process.env.CONTACT_RECEIVER_EMAIL || "sunilbaghel93100@gmail.com";

    // Throw unconfigured error if SMTP values are not present
    if (!host || !user || !pass) {
      console.error("Missing SMTP credentials in environment variables.");
      return NextResponse.json(
        {
          success: false,
          error: "Email service is currently unconfigured. Please set SMTP variables in .env.",
        },
        { status: 500 }
      );
    }

    const transporter = nodemailer.createTransport({
      host,
      port,
      secure: port === 465,
      auth: {
        user,
        pass,
      },
    });

    const mailOptions = {
      from: `"${name} (via Portfolio)" <${user}>`,
      to: receiver,
      replyTo: email,
      subject: `New Project Inquiry: ${projectType} (${budgetRange})`,
      text: `
New portfolio project inquiry from ${name} (${email}).

Project Type: ${projectType}
Budget Range: ${budgetRange}
Timeline: ${timeline}

Message Details:
${message}
      `,
      html: `
        <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e5e7eb; border-radius: 8px; background-color: #fafafa; color: #1f2937;">
          <h2 style="color: #ea580c; border-bottom: 2px solid #ea580c; padding-bottom: 10px; margin-top: 0;">New Project Inquiry</h2>
          
          <p style="margin-bottom: 20px;">You received a new message from the contact form on your portfolio website.</p>
          
          <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px;">
            <tr style="border-bottom: 1px solid #e5e7eb;">
              <td style="padding: 10px 0; font-weight: bold; width: 120px;">From:</td>
              <td style="padding: 10px 0;">${name} (&lt;<a href="mailto:${email}">${email}</a>&gt;)</td>
            </tr>
            <tr style="border-bottom: 1px solid #e5e7eb;">
              <td style="padding: 10px 0; font-weight: bold;">Project Type:</td>
              <td style="padding: 10px 0;">${projectType}</td>
            </tr>
            <tr style="border-bottom: 1px solid #e5e7eb;">
              <td style="padding: 10px 0; font-weight: bold;">Budget:</td>
              <td style="padding: 10px 0;">${budgetRange}</td>
            </tr>
            <tr style="border-bottom: 1px solid #e5e7eb;">
              <td style="padding: 10px 0; font-weight: bold;">Timeline:</td>
              <td style="padding: 10px 0;">${timeline}</td>
            </tr>
          </table>
          
          <div style="background-color: #ffffff; padding: 15px; border-radius: 6px; border: 1px solid #e5e7eb;">
            <strong>Message Details:</strong><br/><br/>
            ${message.replace(/\n/g, '<br/>')}
          </div>
          
          <p style="font-size: 11px; color: #6b7280; margin-top: 30px; text-align: center;">This message was automatically generated by your Next.js portfolio website contact route.</p>
        </div>
      `,
    };

    await transporter.sendMail(mailOptions);

    return NextResponse.json({ success: true });
  } catch (error: any) {
    console.error("Nodemailer error:", error);
    return NextResponse.json(
      { success: false, error: error.message || "Failed to send email." },
      { status: 500 }
    );
  }
}
